Failure test

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -7,6 +7,12 @@ jobs:
         steps:
             - name: step-1
               run: sleep 20
+            - name: step-2
+              id: step-2
+              run: exit 1
+            - name: Runs on Failure
+              if: failure() && steps.step-2.conclusion == 'failure'
+              run: echo "step2 has failed"
             - name: runs on failure
               if: failure()
               run: echo "failure"
@@ -26,5 +32,3 @@ jobs:
         if: failure()
         steps:
             - run: echo "Job 2"
-
-
